server:
  port: 8083

spring:
  application:
    name: activity_service
  data:
    mongodb:
      uri: mongodb://mongo:27017/activity_mongo
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      group-id: activity_group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: java.util,com.example.imageservice